### PR TITLE
fix ide menu not reporting correct required_lines

### LINKED ISSUE #753: ide menu does not correctly apply max_completion_height
## Screenshots/Screencaptures
grafik

when the ide menu is rendered, it reports the required lines without taking the max_completion_height into account which leads to empty lines below the completion

you can assign this to me, ill fix this when i have time (and i might also add max_completion_height for the columnar_menu as well in the same PR)

### PR DESCRIPTION
**Pull request by maxomatic458**
closes #753

### CODE REVIEW

**Comment by stormasm** [comment]
@maxomatic458 I am no longer seeing an issue with nushell and reedline in the latest nushell main...

when I type "str" on my mac it all looks good...

**Comment by maxomatic458** [comment]
@stormasm it only happens when ``max_completion_height`` is less then the number of suggestions

```
name: completion_menu
        only_buffer_difference: false
        marker: ""
        type: {
            layout: ide
            max_completion_height: 5
            ...
        }
```

can you replicate it with this config?

**Comment by stormasm** [comment]
@maxomatic458

see my config below...

I changed it to 5 but for the *str* example I am still seeing the exact same thing as before...
No changes...
I am seeing everything...

```rust
    menus: [
        # Configuration for default nushell menus
        # Note the lack of source parameter
        {
            name: completion_menu
            only_buffer_difference: false
            marker: "| "
            type: {
                layout: columnar
                columns: 4
                col_width: 20     # Optional value. If missing all the screen width is used to calculate column width
                col_padding: 2
                max_completion_height: 5
            }
            style: {
                text: green
                selected_text: { attr: r }
                description_text: yellow
                match_text: { attr: u }
                selected_match_text: { attr: ur }
            }
        }
        {
            name: ide_completion_menu
            only_buffer_difference: false
            marker: "| "
            type: {
                layout: ide
                min_completion_width: 0,
                max_completion_width: 50,
                max_completion_height: 5, # will be limited by the available lines in the terminal
                padding: 0,
                border: true,
                cursor_offset: 0,
                description_mode: "prefer_right"
                min_description_width: 0
                max_description_width: 50
                max_description_height: 10
                description_offset: 1
                # If true, the cursor pos will be corrected, so the suggestions match up with the typed text
                #
                # C:\> str
                #      str join
                #      str trim
                #      str split
                correct_cursor_pos: false
            }
```

**Comment by stormasm** [comment]
https://github.com/nushell/reedline/assets/1809991/deed752f-9f18-4c50-8e60-c50b743afb2d

**Comment by stormasm** [comment]
So I guess the *max_completion_height* is not kicking in either as I am seeing more than 5 ?

**Comment by stormasm** [comment]
hold on my layout is columnar instead of ide let me change it...

**Comment by stormasm** [comment]
@maxomatic458 I was finally able to reproduce the bug 😄 

And your code indeed fixes it !!
Thank you...
And I am going to go ahead and land your PR...

**Comment by stormasm** [comment]
Also one other thing @maxomatic458 
Please remember to create a branch any time you submit a PR...
This way we can test the latest and greatest code...
There was a minor PR that came in after your fix...
So I didn't actually check the latest and greatest code...
But since it was just a print statement it didn't matter....

**Pull request merged**
