### PR TITLE
remove codecov.yml in the reedline repo

### PR DESCRIPTION
**Pull request by stormasm**
I find reviewing PRs with the code coverage turned on incredibly annoying and hard to understand
all of the other code that I need to understand what has changed...

Unless someone really feels strongly about having it in there I am going to remove it....

Thanks !

### CODE REVIEW

**Comment by fdncred** [comment]
I'm wondering if we can disable it without deleting the file just in case we want to easily enable it again?

**Comment by stormasm** [comment]
Here is a copy of the codecov.yml file

```rust
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: reach, diff, files
  behavior: default
  require_base: yes
  require_head: yes
  after_n_builds: 5 # Our test matrix currently has 5 configurations
```

**Comment by stormasm** [comment]
Here is a copy of the associated ci.yml file

```rust
on:
  pull_request:
  push: # Run CI on the main branch after every merge. This is important to fill the GitHub Actions cache in a way that pull requests can see it
    branches:
      - main

name: continuous-integration

jobs:
  build-lint-test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        rust:
          - stable
        # Define the feature sets that will be built here (for caching you define a separate name)
        style: [bashisms, default, sqlite, basqlite, external_printer]
        include:
          - style: bashisms
            flags: "--features bashisms"
          - style: external_printer
            flags: "--features external_printer"
          - style: default
            flags: ""
          - style: sqlite
            flags: "--features sqlite"
          - style: basqlite
            flags: "--features bashisms,sqlite"

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.3.4
      - name: Setup nextest
        uses: taiki-e/install-action@nextest
      - name: Setup cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy ${{ matrix.flags }} --all-targets --all -- -D warnings


      - name: Tests
        run: cargo llvm-cov nextest --all ${{ matrix.flags }} --lcov --output-path lcov.info

      - name: Doctests
        run: cargo test --doc ${{ matrix.flags }}

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
```

**Comment by stormasm** [comment]
Note here is another copy of both files for archival reasons in case we want to change back the settings...

https://github.com/stormasm/nunotes/tree/main/archive

**Comment by stormasm** [comment]
For starters I will just attempt to modify the ci.yml action without actually deleting the codecov.yml file to see if that works and turns off code coverage...

If this doesn't work then we will remove the codecov.yml file...

I wish there was a setting that individuals could set to toggle code coverage on and off when you are looking at PRs.

Then you can review the code with out seeing all of the extraneous code coverage messages which get in the way of trying to understand the code changes...

**Pull request merged**
