### PR TITLE
chore: ensure lockfile up-to-date

### PR DESCRIPTION
**Pull request by tisonkun**
@fdncred fixup something when debugging ..

### CODE REVIEW

**Comment by tisonkun** [comment]
Seems some clippy failure uncaught. Perhaps I can handle it within this PR?

**Comment by tisonkun** [comment]
Push a commit for fix @fdncred

**Comment by tisonkun** [comment]
malformed syntax - https://github.com/nushell/reedline/pull/812/commits/b6eca9f812fd7dcfd23e9c4a7848e01dc2d2b9ac

sorry >_<

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
