### PR TITLE
get correct cursor pos when menu indicator contains newline

### PR DESCRIPTION
**Pull request by maxomatic458**
fixes a bug from #696

### CODE REVIEW

**Comment by fdncred** [comment]
it would be great if we had a test for this to ensure no breakage in the future.

/cc @stormasm

**Comment by stormasm** [comment]
I am not sure this is working correctly as I tested it by modifying your ide_completions example with the following code

```rust
fn add_newline_keybinding(keybindings: &mut Keybindings) {
    // This doesn't work for macOS
    keybindings.add_binding(
        KeyModifiers::ALT,
        KeyCode::Enter,
        ReedlineEvent::Edit(vec![EditCommand::InsertNewline]),
    );
}
```

```rust
add_newline_keybinding(&mut keybindings);
```

similar to the way it works in the demo example...

and then tried typing one letter basically just the "t"

and then add three insert new lines and then hit tab...

See if it works properly on your machine / I am on a Mac

**Comment by maxomatic458** [comment]
should be fixed now 

i found another problem (not specific to my menu)
if you enter a bunch of newlines (so many until the prompt is not visible anymore), then the cursor will enter the menu

here is a screenshot of the columnar menu, basically using the same code as above
grafik

**Comment by maxomatic458** [comment]
> After the third new line is entered I am not seeing test anymore

im not to sure what you mean by that?
can you replicate this in other menus?

**Comment by stormasm** [comment]
So I am seeing strange behavior in the demo example yes....

at the prompt type "h" and then type tab and you see everything as expected....

Now do another test and type "h"

then enter about 5 or 6 new lines and then type "h"

now not everything is there....

**Comment by stormasm** [comment]
So check out the *demo example*

Type an "h" at the prompt and you will see another "h" show up on the screen many lines down probably where the drop down menu ends...

This is a separate issue than the one I mentioned earlier...
But lets address this one first.  Which seems more serious (possibly)...

**Comment by maxomatic458** [comment]
@stormasm so i tried that
[asciicast](https://asciinema.org/a/8kFumdmfLafUSKhETJIVIzwTQ)

but i dont think i was able to replicate it. Did i do something wrong? (did you also try the latest commit?)

if you referred to the cut off at the bottom, then thats intended (you can scroll throught the options that dont fit on the screen)

**Comment by maxomatic458** [comment]
> Type an "h" at the prompt and you will see another "h" show up on the screen many lines down probably where the menu ends...

this might be somewhat intentional, i think thats just a multiline history suggestion. but you cant hit tab to complete it, so i guess thats bugged, and it probably shouldnt even show up if you are not in multiline mode

**Comment by maxomatic458** [comment]
[asciicast](https://asciinema.org/a/zEGYfIVLIlajazUTnKQV7KX5W)

**Comment by stormasm** [comment]
This is your example -> ide_completions.rs modified to show whats going on...

https://github.com/stormasm/nutmp/blob/main/reedline/ide_completions.rs

Note that after the third input line the first line "test" goes away --- this does not seem correct to me...

https://github.com/nushell/reedline/assets/1809991/b826cd5e-44f9-4df0-9139-89d470dddc66

**Comment by stormasm** [comment]
Here is a slightly longer video --- you will note that after the third *InsertNewLine* that test for some reason disappears...


https://github.com/nushell/reedline/assets/1809991/6aeca9d5-40c6-4dee-9cb2-2fef9ea7e71c

**Comment by maxomatic458** [comment]
as soon as i enter a newline i get "NO RECORDS FOUND" until i enter text in the current line,

i start the example
and i press these buttons
t, tab, ALT+ENTER

i also tried this on the columnar menu and it does the same

did you try if this happens for other menus as well?

**Comment by maxomatic458** [comment]
ok i was able to replicate it, by using the unix linebreaks
the same thing happens on the columnar menu as well

**Comment by maxomatic458** [comment]
@stormasm 
ok so it looks like this line here
https://github.com/nushell/reedline/blob/31eaeeb231664b889c92595ff38ead4ccb570766/src/menu/columnar_menu.rs#L546
causes this to only happen on unix (only replace "\n", not "\r\n")

changing the line to
```rs
let trimmed_buffer = editor.get_buffer()
    .replace("\r\n", "  ")
    .replace("\n", " ");
```
will lead to it to work on windows as well. but there is still the issue that some of the suggestion dissapear after a few lines (like your clip above)

i think this might be something for a seperate PR (as this isn't caused by the ide menu, and happens in the other menus as well)

should i open up a seperate issue for this?

**Comment by fdncred** [comment]
Ah, line endings. we've seen that time and time again in reedline and nushell, since we're cross platform. nice catch.

Let's see what @stormasm says but imo, I think I'd put this change
```rust
let trimmed_buffer = editor.get_buffer()
    .replace("\r\n", "  ")
    .replace("\n", " ");
```
in a separate PR in case we have to revert it (or this current PR) for some odd reason.

**Comment by maxomatic458** [comment]
just squeezed this in here as well in preperation for full support to nushell

**Comment by stormasm** [comment]
> Ah, line endings. we've seen that time and time again in reedline and nushell, since we're cross platform. nice catch.
> 
> Let's see what @stormasm says but imo, I think I'd put this change
> 
> ```rust
> let trimmed_buffer = editor.get_buffer()
>     .replace("\r\n", "  ")
>     .replace("\n", " ");
> ```
> 
> in a separate PR in case we have to revert it (or this current PR) for some odd reason.

I will defer to @fdncred for the call on what to do here as I don't know what the best way to go is...

**Comment by fdncred** [comment]
@maxomatic458 can you open another pr for that line ending change? We'll land that real quick.

**Comment by maxomatic458** [comment]
@fdncred i just made #709

**Comment by fdncred** [comment]
does this need to be rebased to accomodate the line ending pr?

**Comment by maxomatic458** [comment]
@fdncred i don't think so

**Comment by fdncred** [comment]
Ok. Let's give it a try.

**Pull request merged**
