### PR TITLE
fix description line not truncating in columnar menu

### PR DESCRIPTION
**Pull request by maxomatic458**
fixes https://github.com/nushell/reedline/issues/738

### CODE REVIEW

**Comment by fdncred** [comment]
Do you have a nushell branch that I can test this out in?

**Comment by maxomatic458** [comment]
not right now, ill finish this PR tomorrow and make a nushell branch so you can test it.

**Comment by fdncred** [comment]
ok, sounds good. thank you!

**Comment by maxomatic458** [comment]
@fdncred the PR should be ready now, you can test it here https://github.com/maxomatic458/nushell/tree/testing

**Comment by fdncred** [comment]
Looks good. thanks!

**Pull request merged**
