### PR TITLE
fix: make traits `Send`

### LINKED ISSUE #220: traits are not thread safe
Would it be possible to have the traits to be thread safe? This is a blocker for Deno to switch away from rustyline to reedline, as we spawn a new tokio thread for each read_line call

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #220

### CODE REVIEW

**Comment by sholderbach** [comment]
Thanks! Looks good to me. CI just failed on `cargo fmt`. 

@jntrnr can we think of any reason why we would want something not necessarily `Sync`?

**Comment by bartlomieju** [comment]
Maybe a test case in `src/engine.rs` could be useful? Something like:
```rust
#[test]
fn thread_safe() {
  fn f<S: Send + Sync>(_: S) {}
  f(Reedline::create().unwrap());
}
```

**Comment by fdncred** [comment]
can someone add that test case please?

**Comment by jntrnr** [comment]
@sholderbach - that's a good question

@crowlKats - do you need both Send + Sync or just Send? I'm not as familiar with tokio and its requirements.

**Comment by crowlKats** [comment]
Test added, and it seems just `Send` is required, adjusted the PR

**Comment by sholderbach** [comment]
Thanks!

**Comment by jntrnr** [comment]
Looks good. Thanks @crowlKats!

**Comment by bartlomieju** [comment]
Thanks folks, much appreciated! We'll get back to you after preliminary tests.

**Pull request merged**
