### PR TITLE
Typed text style

### LINKED ISSUE #724: add "typed-text-style" to MenuTextStyle
this is a concept from the nushell discord by "bisaknosp"
grafik

https://github.com/nushell/reedline/blob/03a1baba6c2403e172e7eb1d4ad0c3175376c916/src/menu/mod.rs#L16-L23

### PR DESCRIPTION
**Pull request by maxomatic458**
closes #724

Adds ``selected_match_style`` and ``match_style`` to ``MenuTextStyle``.

IdeMenu
grafik

ColumnarMenu
grafik

### CODE REVIEW

**Comment by maxomatic458** [comment]
ill do some more testing to make sure it doesnt mess with #691

then i'll mark this PR as ready

**Comment by stormasm** [comment]
@maxomatic458 thanks I tested this out and it looks good 👍

**Comment by fdncred** [comment]
How do we get this enabled in nushell? Is there a PR already that I'm missing?

**Comment by maxomatic458** [comment]
@fdncred im making one right now, but i forgot to add the needed builder functions #731. <- once this is merged ill open the PR on nushell

**Comment by maxomatic458** [comment]
@fdncred i just opened a PR on nushell https://github.com/nushell/nushell/pull/11670

**Pull request merged**
