### PR TITLE
line buffer editor

### LINKED ISSUE #409: Make it possible to edit the current command in an editor (nushell)
This was originally a feature request for nushell:
https://github.com/nushell/nushell/issues/5329

Please make it possible to edit the current command in an editor (e.g. VIM).
I.e. add support for something like ZSH's `edit-command-line`, bound to a keyboard shortcut.

I love this feature from ZSH (and BASH), and without it I can't switch to nushell.
I have a workflow where I essentially store lots of small scripts in my ZSH history. For example, I have a script to build and test a set of binaries, and the script is maybe 20 lines. Because I have several projects with similar layouts, it's quick for me to create a new project, reverse search to find a command (script) similar to the one I want, quickly edit it in VIM, and then run it.

You might think the answer is to write these scripts to files, but it's actually much faster to keep them in my ZSH history: 1) I can quickly find just what I want using reverse search, 2) I can effortlessly keep multiple "versions" of the scripts without using git, 3) some commands are complicated enough they benefit from a real editor but they're not worth saving to a file.

Here's a GIF that shows a bit of what I mean:
https://dev.to/chhajedji/bash-edit-command-in-your-editor-and-execute-directly-30ef

### PR DESCRIPTION
**Pull request by elferherrera**
Introduces a new event to open a line editor to edit the line buffer

Note. There is an issue that I cannot figure out. After you open the line buffer (ctr + e), edit your line and save the result, if you press `ctr+c` there is a panic in reedline. I've been looking everywhere but I cannot find where it is coming from.  Any suggestions on where that error could come from?

closes #409

### CODE REVIEW

**Comment by kubouch** [comment]
Have you tried printing the backtrace? That should tell you where the error originates from.

**Comment by elferherrera** [comment]
Yeap. Tried that but to backtrace is printed

**Comment by kubouch** [comment]
Have you run it with `RUST_BACKTRACE=1`? It should print a backtrace.

**Comment by elferherrera** [comment]
Tried and nothing comes out

**Comment by kubouch** [comment]
That's super weird. How could it not print a backtrace? Are you sure you tried with a debug build? `RUST_BACKTRACE=full`?

**Comment by elferherrera** [comment]
image

**Comment by elferherrera** [comment]
I was afraid it was going to be that case. Well, I guess we can merge it and add it to nu

**Pull request merged**
