### PR TITLE
Move ctrl+a & ctrl+e to common navigation binds

### PR DESCRIPTION
**Pull request by Artturin**

### CODE REVIEW

**Comment by sholderbach** [comment]
As far as I remember neither `zsh` with `bindkey -v` nor `vim` do that by default but it's not that much of an issue for me ;)

**Comment by Artturin** [comment]
> As far as I remember neither `zsh` with `bindkey -v` nor `vim` do that by default but it's not that much of an issue for me ;)

It should, at least, be available in insert mode.
If in the future it should be something else in normal mode then it can be overridden

**Comment by Artturin** [comment]
tested by adding
``
[patch."https://github.com/nushell/reedline"]
reedline = { path = "../reedline"}
```

to the nushell Cargo.toml

**Comment by sholderbach** [comment]
Good catch with the `DeleteWord` vs `BackspaceWord`

**Pull request merged**
