### PR TITLE
list things with `reedline --list`

### PR DESCRIPTION
**Pull request by fdncred**
This is a quick hack to list things. It's totally meant as a conversation starter and not a finished implementation. Feel free to hack on and submit to this PR.

If this was to be used exclusively to pass information to e-q we could `impl Display for blah_enum` and output the text that the keybindings in e-q want to see when parsed. I prototyped that here too.

I'm thinking something like this needs to be turned into several exposed functions so that, in e-q, we can call `get_modifiers()`, `get_modes()`, `get_keycodes()`, etc. and show them to the user so they know what is map-able via keybindings.

```rust
impl Display for PromptEditMode {
    fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
        match self {
            PromptEditMode::Default => write!(f, "default"),
            PromptEditMode::Emacs => write!(f, "emacs"),
            PromptEditMode::Vi(_) => write!(f, "vi_normal\nvi_insert"),
            PromptEditMode::Custom(s) => write!(f, "{}", format!("custom_{}", s)),
        }
    }
}
```

```
    ~/src/forks/reedline   list_things  cargo r -- --list                                               ✔  01:40:41 PM 
   Compiling reedline v0.2.0 (/Users/fdncred/src/forks/reedline)
    Finished dev [unoptimized + debuginfo] target(s) in 1.33s
     Running `target/debug/reedline --list`
--Key Modifiers--
Alt
Control
Shift
None

--Modes--
Default
Emacs
Vi_Normal
Vi_Insert
Custom_

--Key Codes--
Backspace
Enter
Left
Right
Up
Down
Home
End
PageUp
PageDown
Tab
BackTab
Delete
Insert
F(1)
F(2)
F(3)
F(4)
F(5)
F(6)
F(7)
F(8)
F(9)
F(10)
F(11)
F(12)
Char('a')
Null
Esc

--Reedline Events--
None
HistoryHintComplete
HistoryHintWordComplete
ActionHandler
CtrlD
CtrlC
ClearScreen
Enter
Esc
Mouse
Resize(0, 0)
Edit([])
Repaint
PreviousHistory
Up
Down
Right
Left
NextHistory
SearchHistory
Paste([])
Multiple([])
UntilFound([])
Menu("")
MenuNext
MenuPrevious
MenuUp
MenuDown
MenuLeft
MenuRight
MenuPageNext
MenuPagePrevious

--Edit Commands--
MoveToStart
MoveToLineStart
MoveToEnd
MoveToLineEnd
MoveLeft
MoveRight
MoveWordLeft
MoveWordRight
InsertChar('\u{0}')
InsertString("")
Backspace
Delete
BackspaceWord
DeleteWord
Clear
ClearToLineEnd
CutCurrentLine
CutFromStart
CutFromLineStart
CutToEnd
CutToLineEnd
CutWordLeft
CutWordRight
PasteCutBufferBefore
PasteCutBufferAfter
UppercaseWord
LowercaseWord
CapitalizeChar
SwapWords
SwapGraphemes
Undo
Redo
CutRightUntil('\u{0}')
CutRightBefore('\u{0}')
MoveRightUntil('\u{0}')
MoveRightBefore('\u{0}')
CutLeftUntil('\u{0}')
CutLeftBefore('\u{0}')
MoveLeftUntil('\u{0}')
MoveLeftBefore('\u{0}')

--Default Keybindings--
mode: emacs, key_modifier(s): CONTROL, key_code: Char('e'), event: Edit([MoveToLineEnd])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('z'), event: Edit([Undo])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('g'), event: Edit([Redo])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('c'), event: CtrlC
mode: emacs, key_modifier(s): CONTROL, key_code: Char('t'), event: Edit([SwapGraphemes])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('p'), event: UntilFound([MenuUp, Up])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('n'), event: UntilFound([MenuDown, Down])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('d'), event: CtrlD
mode: emacs, key_modifier(s): NONE, key_code: Right, event: UntilFound([HistoryHintComplete, MenuRight, Right])
mode: emacs, key_modifier(s): NONE, key_code: Delete, event: Edit([Delete])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('l'), event: ClearScreen
mode: emacs, key_modifier(s): NONE, key_code: Backspace, event: Edit([Backspace])
mode: emacs, key_modifier(s): ALT, key_code: Left, event: Edit([MoveWordLeft])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('u'), event: Edit([CutFromStart])
mode: emacs, key_modifier(s): ALT, key_code: Char('l'), event: Edit([LowercaseWord])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('y'), event: Edit([PasteCutBufferBefore])
mode: emacs, key_modifier(s): ALT, key_code: Char('m'), event: Edit([BackspaceWord])
mode: emacs, key_modifier(s): NONE, key_code: End, event: Edit([MoveToLineEnd])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('h'), event: Edit([Backspace])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('b'), event: UntilFound([MenuLeft, Left])
mode: emacs, key_modifier(s): NONE, key_code: Esc, event: Esc
mode: emacs, key_modifier(s): NONE, key_code: Home, event: Edit([MoveToLineStart])
mode: emacs, key_modifier(s): NONE, key_code: Down, event: UntilFound([MenuDown, Down])
mode: emacs, key_modifier(s): NONE, key_code: Left, event: UntilFound([MenuLeft, Left])
mode: emacs, key_modifier(s): ALT, key_code: Char('d'), event: Edit([CutWordRight])
mode: emacs, key_modifier(s): ALT, key_code: Char('u'), event: Edit([UppercaseWord])
mode: emacs, key_modifier(s): ALT, key_code: Delete, event: Edit([DeleteWord])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('f'), event: UntilFound([HistoryHintComplete, MenuRight, Right])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('r'), event: SearchHistory
mode: emacs, key_modifier(s): NONE, key_code: Up, event: UntilFound([MenuUp, Up])
mode: emacs, key_modifier(s): ALT, key_code: Char('b'), event: Edit([MoveWordLeft])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('w'), event: Edit([CutWordLeft])
mode: emacs, key_modifier(s): CONTROL, key_code: Right, event: UntilFound([HistoryHintWordComplete, Edit([MoveWordRight])])
mode: emacs, key_modifier(s): ALT, key_code: Backspace, event: Edit([BackspaceWord])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('a'), event: Edit([MoveToLineStart])
mode: emacs, key_modifier(s): ALT, key_code: Right, event: UntilFound([HistoryHintWordComplete, Edit([MoveWordRight])])
mode: emacs, key_modifier(s): CONTROL, key_code: Char('k'), event: Edit([CutToEnd])
mode: emacs, key_modifier(s): ALT, key_code: Char('c'), event: Edit([CapitalizeChar])
mode: vi_normal, key_modifier(s): NONE, key_code: End, event: Edit([MoveToLineEnd])
mode: vi_normal, key_modifier(s): CONTROL, key_code: Char('l'), event: ClearScreen
mode: vi_normal, key_modifier(s): CONTROL, key_code: Char('b'), event: UntilFound([MenuLeft, Left])
mode: vi_normal, key_modifier(s): CONTROL, key_code: Char('r'), event: SearchHistory
mode: vi_normal, key_modifier(s): ALT, key_code: Delete, event: Edit([DeleteWord])
mode: vi_normal, key_modifier(s): NONE, key_code: Up, event: UntilFound([MenuUp, Up])
mode: vi_normal, key_modifier(s): ALT, key_code: Left, event: Edit([MoveWordLeft])
mode: vi_normal, key_modifier(s): CONTROL, key_code: Char('p'), event: UntilFound([MenuUp, Up])
mode: vi_normal, key_modifier(s): CONTROL, key_code: Char('c'), event: CtrlC
mode: vi_normal, key_modifier(s): CONTROL, key_code: Char('f'), event: UntilFound([HistoryHintComplete, MenuRight, Right])
mode: vi_normal, key_modifier(s): NONE, key_code: Backspace, event: Edit([Backspace])
mode: vi_normal, key_modifier(s): ALT, key_code: Backspace, event: Edit([BackspaceWord])
mode: vi_normal, key_modifier(s): ALT, key_code: Right, event: UntilFound([HistoryHintWordComplete, Edit([MoveWordRight])])
mode: vi_normal, key_modifier(s): NONE, key_code: Left, event: UntilFound([MenuLeft, Left])
mode: vi_normal, key_modifier(s): NONE, key_code: Right, event: UntilFound([HistoryHintComplete, MenuRight, Right])
mode: vi_normal, key_modifier(s): CONTROL, key_code: Char('n'), event: UntilFound([MenuDown, Down])
mode: vi_normal, key_modifier(s): NONE, key_code: Down, event: UntilFound([MenuDown, Down])
mode: vi_normal, key_modifier(s): NONE, key_code: Esc, event: Esc
mode: vi_normal, key_modifier(s): NONE, key_code: Delete, event: Edit([Delete])
mode: vi_normal, key_modifier(s): NONE, key_code: Home, event: Edit([MoveToLineStart])
mode: vi_insert, key_modifier(s): NONE, key_code: End, event: Edit([MoveToLineEnd])
mode: vi_insert, key_modifier(s): NONE, key_code: Delete, event: Edit([Delete])
mode: vi_insert, key_modifier(s): ALT, key_code: Right, event: UntilFound([HistoryHintWordComplete, Edit([MoveWordRight])])
mode: vi_insert, key_modifier(s): NONE, key_code: Home, event: Edit([MoveToLineStart])
mode: vi_insert, key_modifier(s): CONTROL, key_code: Char('r'), event: SearchHistory
mode: vi_insert, key_modifier(s): NONE, key_code: Backspace, event: Edit([Backspace])
mode: vi_insert, key_modifier(s): NONE, key_code: Left, event: UntilFound([MenuLeft, Left])
mode: vi_insert, key_modifier(s): NONE, key_code: Right, event: UntilFound([HistoryHintComplete, MenuRight, Right])
mode: vi_insert, key_modifier(s): CONTROL, key_code: Char('b'), event: UntilFound([MenuLeft, Left])
mode: vi_insert, key_modifier(s): ALT, key_code: Delete, event: Edit([DeleteWord])
mode: vi_insert, key_modifier(s): NONE, key_code: Down, event: UntilFound([MenuDown, Down])
mode: vi_insert, key_modifier(s): CONTROL, key_code: Char('p'), event: UntilFound([MenuUp, Up])
mode: vi_insert, key_modifier(s): CONTROL, key_code: Char('l'), event: ClearScreen
mode: vi_insert, key_modifier(s): CONTROL, key_code: Char('n'), event: UntilFound([MenuDown, Down])
mode: vi_insert, key_modifier(s): CONTROL, key_code: Char('c'), event: CtrlC
mode: vi_insert, key_modifier(s): ALT, key_code: Backspace, event: Edit([BackspaceWord])
mode: vi_insert, key_modifier(s): NONE, key_code: Esc, event: Esc
mode: vi_insert, key_modifier(s): NONE, key_code: Up, event: UntilFound([MenuUp, Up])
mode: vi_insert, key_modifier(s): CONTROL, key_code: Char('f'), event: UntilFound([HistoryHintComplete, MenuRight, Right])
mode: vi_insert, key_modifier(s): ALT, key_code: Left, event: Edit([MoveWordLeft])
```

### CODE REVIEW

**Comment by elferherrera** [comment]
What about moving this command to eq? We can present the data as a table

**Comment by elferherrera** [comment]
What do you think about this list
image

**Comment by elferherrera** [comment]
for that command to work, I would need to merge this [PR](https://github.com/nushell/reedline/pull/291) which introduces a new dependency. 
The command in EQ is implemented in this [PR](https://github.com/nushell/engine-q/pull/906)

@sholderbach @jntrnr are you ok with adding this dependency to reedline?

**Comment by fdncred** [comment]
@elferherrera, I've always intended the listing to be in engine-q. However I thought it was better to implement these `get_` commands in reedline so other people who use reedline can easily benefit from them without having to reinvent the wheel.

* get_all_keybinding_info
* get_reedline_edit_commands
* get_reedline_keybinding_modifiers
* get_reedline_keycodes
* get_reedline_prompt_edit_modes
* get_reedline_reedline_events

Items that we still need to address.
1. I have no problem with you implementing similar code but I believe your implementation is missing some of these listed above. 
2. I'm also thinking we need to implement display so we have a better control of the output so we don't get things like `CutRightUntil('\u{0}')`.
3. I've also been thinking about another function that we need to have, `get_current_keybindings` that lists what's bound by defaults named something like `keybinding defaults` in engine-q.
4. Along with listing the defaults it may be good to have a `Option<Description>` on explains what the keybinding is for. People can use None if they don't want to hassle with it but if you do use it, when you call `get_current_keybindings` it will list how it's bound and a short description of what it's for.
5. We need to let the engine-q user know somehow that `get_reedline_edit_commands` are for use with the `edit:` keyword and the `get_reedline_reedline_events` are for use with the `send:` keyword as demonstrated in the example below.

```
{
    name: prev_shell
    modifier: control
    keycode: char_y
    mode: vi_insert
    event: [
      { edit: { cmd: clear } }
      { edit: { cmd: insertchar value: p } }
      { send: enter }
    ]
  }
```

**Comment by elferherrera** [comment]
I see your point and makes lots of sense. I wouldn't mind merging this pr to have access to the functions for the command to work

**Comment by fdncred** [comment]
> I see your point and makes lots of sense. I wouldn't mind merging this pr to have access to the functions for the command to work

same. did you see the thing I just added? it gets the default keybindings. this would look great in a nushell table. :) I updated the issue with the output above.

**Comment by elferherrera** [comment]
All the functions make sense to me. The default one is a bit tricky because if you want to do something with it, you will have to parse the string again. I think we can merge it and keep working on it. Let's see what @jntrnr and @sholderbach have to say

**Comment by fdncred** [comment]
> The default one is a bit tricky because if you want to do something with it, you will have to parse the string again.

ya, we can return whatever we need to make it easy like `mode|modifiers|events` or a `Vec<(mode, modifiers, events)>` - whatever we need.

**Comment by fdncred** [comment]
I updated the `get_reedline_keybinding_defaults` to return a `Vec<(String, String, String, String)>` with my last push. So, this should make it easier to parse.

**Pull request merged**
