### PR TITLE
Support "token by token" hint completion

### PR DESCRIPTION
**Pull request by sholderbach**
Hints can now be completed partially

Keybindings: `Alt-right` `Alt-f` `Ctrl-right`

Uses whitespace as token/word boundary for now

### CODE REVIEW

**Comment by elferherrera** [comment]
Do you mind adding the same keybinding for vi insert mode?

**Comment by sholderbach** [comment]
Vi insert is no problem, for Vi normal we probably have to be a bit more elegant

**Comment by elferherrera** [comment]
Im wondering how detailed should vi mode be

**Comment by sholderbach** [comment]
Yeah our current vi behavior is not compliant when it comes to word boundaries, but I consider that a problem for another day. Either procrastination or complaints by vi purists will determine the timeline on that :D

**Comment by jntrnr** [comment]
Let's go ahead and merge this and play with it. We might want to compare against fish as we do, just see if folks coming from other shells will have something familiar

**Comment by fdncred** [comment]
just lovely. thanks stefan!

**Pull request merged**
