### PR TITLE
Fix `prompt_start_row` reset to 0 when opening a file without newline in Nushell

### PR DESCRIPTION
**Pull request by nibon7**
Try to fix nushell/nushell#11399

### CODE REVIEW

**Comment by amtoine** [comment]
@nibon7 
is it possible to test this patch with one of the Reedline examples?

**Comment by nibon7** [comment]
It could be reproduced by applying a patch below :sweat_smile: 

```diff
diff --git a/examples/demo.rs b/examples/demo.rs
index 2e7a402..00d3dae 100644
--- a/examples/demo.rs
+++ b/examples/demo.rs
@@ -201,6 +201,7 @@ fn main() -> std::io::Result<()> {
                     continue;
                 }
                 println!("Our buffer: {buffer}");
+                print!(" ");
                 #[cfg(any(feature = "sqlite", feature = "sqlite-dynlib"))]
                 if !buffer.is_empty() {
                     line_editor
```

**Comment by sholderbach** [comment]
That change makes sense and fixes your provided repro. Thanks @nibon7

**Comment by fdncred** [comment]
I think this PR is breaking things. I put some notes about it here https://github.com/nushell/nushell/pull/11406#issuecomment-1869591405. There's a gif on discord in that link.

**Comment by amtoine** [comment]
> I think this PR is breaking things. I put some notes about it here [nushell/nushell#11406 (comment)](https://github.com/nushell/nushell/pull/11406#issuecomment-1869591405). There's a gif on discord in that link.
>
i suspect https://github.com/nushell/reedline/pull/675 is the real responsible for these bugs :thinking:

**Comment by fdncred** [comment]
We probably need to revert this one too.

**Comment by sholderbach** [comment]
@danielsomerfield @nibon7 sounds like we need to figure out a way to make the new prompt position logic from #675 to work without causing either https://github.com/nushell/nushell/pull/11406#issuecomment-1869591405 or https://github.com/nushell/nushell/issues/11399

**Pull request merged**
